# Generated by Django 4.1.4 on 2022-12-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='day_birth',
        ),
    ]
